# Discussion 

## Conclusion

In this paper, a jackknife estimator for multiply imputed outcome variables under the concern of uncongeniality was presented. The proposed estimator was compared to two alternative approaches in the literature employing a Monte Carlo simulation study, where all methods were evaluated on the bias of their point estimates, the width and coverage of their confidence intervals, and computational time. All procedures were found to slightly over-cover, suggesting conservative variance estimates, with Rubin's rules resulting in the broadest confidence intervals with significant over-coverage compared to the nominal level. In contrast, the two resampling-based approaches examined resulted in a substantial decline in confidence interval width, with the proposed jackknife estimator providing the narrowest confidence intervals by a wide margin while still attaining near-nominal coverage. 

Unsurprisingly, Rubin's rules were the least computationally costly approach among the ones examined; however, given its downward-biased point estimates and wide confidence intervals, particularly in instances where uncongeniality is a concern, resampling-based robust methods should be preferred. Among the two resampling-based methods examined, the bootstrap approach took nearly ten times longer per iteration, which was a surprising observation, as both the jackknife and bootstrap methods utilized the same number of imputations, iterations, and subsamples. From a computational perspective, there is no evident reason why the bootstrap method should take nearly ten times longer than the proposed jackknife estimator. It is possible that the R package utilized for the bootstrap approach, *bootImpute*, is not optimized with speed concerns in mind. However, neither was the jackknife estimator. In both instances, the most time-consuming aspect of the processes was the imputation of the subsamples generated, either via bootstrap resampling or jackknife resampling, done with the same R package, *mice*, and the same parameters, number of iterations, and imputations. Given that the foregoing steps took place under identical conditions, perhaps a different aspect of the two approaches could explain the discrepancy noted. 

Nevertheless, given the superior performance of the jackknife estimator noted, alongside its computational efficiency, the recommendation to replace Rubin's rules as the de facto standard in small, multiply imputed datasets with our proposed estimator is made. 

## Future Directions

Perhaps the most significant issue noted with the jackknife estimator was a slightly higher coverage probability compared to the nominal. Although the Monte Carlo error may partially explain this observation, alternative confidence interval construction approaches could be considered to yield more appropriate coverage. Namely, it is possible that a confidence interval could be generated by examining various values calculated based on Rubin's rules, such as the fraction of missing information, relative efficiency, and relative increase in variance. The aforestated statistics could be used to appropriately model the uncertainty in the imputation process, which, in turn, could be used to generate confidence intervals in a semi-parametric manner. 

Otherwise, although the proposed estimator was efficient even with a small number of subsamples and imputations, alternative confidence interval constructions could allow one to utilize even fewer subsamples while still attaining nominal coverage, which may make the proposed method even more computationally feasible. 